# Generated by Django 6.0.3 on 2026-04-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='chapter_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language_name_en',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='language',
            name='language_name_ru',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='networkstudent',
            name='network_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='networkstudent',
            name='network_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='networkteacher',
            name='network_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='networkteacher',
            name='network_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_name_en',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='option_name_ru',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_name_ru',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
