# Generated by Django 6.0.3 on 2026-04-14 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_teacher_options_lesson_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='update',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='networkstudent',
            old_name='teacher',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_register',
            new_name='date_registered',
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_teacher', to='course_app.teacher'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name='дедлайн'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_lesson', to='course_app.lesson'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course_app.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to='course_app.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('начальный', 'начальный'), ('средний', 'средний'), ('продвинутый', 'продвинутый')], max_length=32),
        ),
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.ManyToManyField(related_name='subcategory_course', to='course_app.subcategory'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='course_app.chapter'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_chapter', to='course_app.chapter'),
        ),
        migrations.AlterField(
            model_name='networkteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks_teacher', to='course_app.teacher'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_option', to='course_app.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_exam', to='course_app.exam'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='course_app.course'),
        ),
        migrations.AlterField(
            model_name='reviewlike',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_like', to='course_app.review'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(related_name='student_course', to='course_app.course'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_sub', to='course_app.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.CharField(max_length=62, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name_en',
            field=models.CharField(max_length=62, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name_ru',
            field=models.CharField(max_length=62, null=True, unique=True),
        ),
    ]
